Provide a rake task for syncing shared SCSS
OfficeForProductSafetyAndStandards/product-safety-database pull request #1992
Opened 2022-08-11 09:41 UTC by stdstaff

Part of the development process involves taking the latest SCSS files from:
https://github.com/OfficeForProductSafetyAndStandards/product-safety-database-prototypes/tree/master/app/assets/sass/opss
And comitting them to the codebase.

This PR adds a `rake` task to automate this process, and the manual change involved in it. It also includes the latest versions of these files.

```
$ bin/rails assets:sync_opss_styles

$ git status
	modified:   app/assets/stylesheets/opss/_opss-pagination.scss
	modified:   app/assets/stylesheets/opss/_opss-psd.scss
	modified:   app/assets/stylesheets/opss/_opss-search.scss
	modified:   app/assets/stylesheets/opss/_opss-shared.scss

# Inspect and commit changes...
```

2022-08-11 09:50 UTC, KyleMacPherson approved these changes

2022-08-11 10:06 UTC, slorek requested changes
This is a helpful utility but represents one designer's preferred workflow, and is not typical of the team's way of working. We should manage changes to the CSS via pull requests, ideally alongside the functional changes they support. Let's have a discussion with the team about why we think this is needed.

2022-08-11 13:34 UTC, stdstaff commented on app/assets/stylesheets/opss/_opss-shared.scss
> +    } */
There's a number of comments and a lot of extraneous whitespace in the upstream project but I am having to commit this as otherwise we would battle linting it with every sync (we are currently doing this manually, ideally we could improve the quality of the upstream files).

2023-01-12 16:26 UTC, stdstaff commented
Another approach to this is drafted here: https://github.com/OfficeForProductSafetyAndStandards/product-safety-database-prototypes/pull/142

2023-01-12 16:28 UTC, closed without merging