Investigation product data migration
OfficeForProductSafetyAndStandards/product-safety-database pull request #2046
Opened 2022-09-21 12:55 UTC by KyleMacPherson

https://trello.com/c/I3imrFNG/1520-data-migration-of-4-pieces-of-case-specific-info-from-product-to-case

## Description
Migrate investigation product data from the products table to the investigation products table and remove references to these removed columns

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2022-09-21 17:38 UTC, stdstaff commented on app/models/product.rb
> -  }
We probably need a new model class, `InvestigationProduct` that has these enums, and has the `redacted_export_with` declaration inside, so these fields continue to be exported from their new table.

2022-09-22 09:12 UTC, stdstaff approved these changes

2022-09-22 09:42 UTC, slorek requested changes
I think we need to handle the fields differently in the `AddProductToCase` service and the products in the seeds file.

2022-09-22 09:42 UTC, slorek commented on lib/tasks/rapex_import.rake
> -      batch_number: field_from_notification(notification, "batchNumber_barcode"),
I think we should add this to the `create_investigation_product` method in this task.

2022-09-22 11:23 UTC, nasirkhanbeis approved these changes
Had a quick look at the review app, regression tested cases and product creation. looks all good.

2022-09-22 12:42 UTC, slorek approved these changes

2022-09-22 12:43 UTC, merged