feat/PSD-2482-view-prod-summary-from-notif-summary
OfficeForProductSafetyAndStandards/product-safety-database pull request #3010
Opened 2024-04-16 13:17 UTC by tahir-khalid

## Description
As a PSD user I want to view product from a notification summary post submission so that I can check Product details without navigating away from the summary page

## Screen-shots or screen-capture of UI changes

### Before:
![image](https://github.com/OfficeForProductSafetyAndStandards/product-safety-database/assets/72029455/68017c3b-87bb-411a-b4ef-05c5b07c15ec)

### After:

![image](https://github.com/OfficeForProductSafetyAndStandards/product-safety-database/assets/72029455/4b231755-833e-4a03-8573-979fc9f1f73b)

2024-04-16 14:55 UTC, alan-at-work reviewed
Looks good, some ideas which could clean up the code, WDYT?

2024-04-16 14:55 UTC, alan-at-work commented on app/helpers/notifications/create_helper.rb
> +        if is_link
`investigation_product_units_with_link` and `investigation_product_units` isn't that clear from their names. 
Could we rename them to better reflect their purpose?

Maybe extract these out and do 

```
def with_link(investigation_product, units_text)
  "#{link_to investigation_product.product.decorate.name_with_brand, product_path(investigation_product.product_id) }  #{units_text}"
end
```

```
def without_link(investigation_product, units_text)
  "#{investigation_product.product.decorate.name_with_brand}: #{units_text}"
end
```

2024-04-16 14:55 UTC, alan-at-work commented on app/helpers/notifications/create_helper.rb
> +    def number_of_affected_units(investigation_products, is_link: false)
I would start to look a cleaning this up to make it more maintainable and easier to read?

Maybe something like this...

```
def number_of_affected_units(investigation_products, is_link: false)
  investigation_products.map do |investigation_product|
    units_text = units_text_for_product(investigation_product)
    is_link ? with_link(investigation_product, units_text) : without_link(investigation_product, units_text)
  end.join("<br>")
end
```

2024-04-16 14:55 UTC, alan-at-work commented on app/helpers/notifications/create_helper.rb
>          units = case investigation_product.affected_units_status
Bring this out too 

```
def units_text_for_product(investigation_product)
  case investigation_product.affected_units_status
  when "exact"
    investigation_product.number_of_affected_units
  when "approx"
    "Approximately #{investigation_product.number_of_affected_units}"
  when "unknown"
    "Unknown"
  when "not_relevant"
    "Not relevant"
  else
    "Not provided"
  end
end
```

2024-04-16 14:56 UTC, alan-at-work commented
Also need to use rubocop to help fix the rouge whitespace

2024-04-18 11:57 UTC, alan-at-work commented
rebased with main

2024-04-18 12:17 UTC, alan-at-work approved these changes
Changes look good for this initial bit of work.

2024-04-19 08:46 UTC, rubenarakelyan requested changes

2024-04-19 08:46 UTC, rubenarakelyan commented on app/helpers/notifications/create_helper.rb
> +      "#{link_to "#{investigation_product.product.psd_ref} - #{investigation_product.product.decorate.name_with_brand}", product_path(investigation_product.product_id), target: '_blank', rel: 'nofoll
There should be a colon here to match with the "no link" version

2024-04-19 08:46 UTC, rubenarakelyan commented on docker/env.psd
> +DATABASE_URL=postgresql://postgres:password@db:5432
Don't think this should be here...

2024-04-19 09:47 UTC, tahir-khalid commented on docker/env.psd
> +DATABASE_URL=postgresql://postgres:password@db:5432
IDE being crap have restored the file.

2024-04-22 10:56 UTC, merged