PSD-2663: Refactor Investigation Forms
OfficeForProductSafetyAndStandards/product-safety-database pull request #3074
Opened 2024-06-19 09:41 UTC by Nashar101

Description: Refactored forms located in the investigations views to use the GOVUKDesignSystemFormBuilder builder for the form.
Because some form models are not descendants of ApplicationRecord and are ActiveModels and they have date attributes, I had to handle the date field in the forms as the date field was sending an array of 3 items and they did not know how to handle it.
Fixed the model specs to reflect these changes.

This pull request addresses PSD-2665, PSD-2669, PSD-2670, PSD-2671, PSD-2752, PSD-2672.

2024-06-19 12:44 UTC, alan-at-work commented
This is really great work @Nashar101, but I think it will take a little bit to get through as a review :) please bare with :D

2024-06-24 11:59 UTC, tahir-khalid requested changes
Approving

2024-06-24 11:59 UTC, tahir-khalid commented on config/database.yml
Do we need the password in the database config file (I have been told off by Meera for leaving it in there lol)?

2024-06-24 12:22 UTC, Nashar101 commented on config/database.yml
No, I don't know why it was changed I did not add it to files to commit, I will rectify this change

2024-06-24 12:53 UTC, alan-at-work requested changes
There seems to be a lot of files her from other commits other than your own work. We need to look at why this is happening as you should only have you work in your PR.

2024-06-24 12:53 UTC, alan-at-work commented on config/database.yml
> +  password: "password"
remove please :) and rebase

2024-06-24 12:53 UTC, alan-at-work commented on app/decorators/audit_activity/corrective_action/update_decorator.rb
> +    Rails.logger.debug { "Legislation Metadata: #{metadata}" } # Debugging output
Why are you including these files? I am suspecting a rebase was not done properly?

2024-06-24 12:53 UTC, alan-at-work commented on app/models/notification_export.rb
> +        row_data = serialize_notification(notification.decorate)
Why are you including these files? I am suspecting a rebase was not done properly?

2024-06-24 12:57 UTC, Nashar101 commented on app/models/notification_export.rb
> +        row_data = serialize_notification(notification.decorate)
I do not know why it was not part of the files which had conflicts, the files which had conflicts were the ones which i modified I did not touch this file.

2024-06-26 12:01 UTC, alan-at-work commented
There are so many issues with this branch, not your fault or code. But I think we need to look to break these down into smaller chunks of work. I will have a think on how we can do this :) 

Then it would be best to do each part as its own branch/PR

2024-06-28 13:59 UTC, closed without merging