Fix/psd 2754 bulk upload notification status to be draft
OfficeForProductSafetyAndStandards/product-safety-database pull request #3160
Opened 2024-08-09 13:48 UTC by tahir-khalid

[PSD-2874](https://regulatorydelivery.atlassian.net/browse/PSD-2874)

## Description
Ensured notification is in submitted state until its actually submitted at the end of the journey.

## Screen-shots or screen-capture of UI changes

![image](https://github.com/user-attachments/assets/45f66be9-5398-4822-9944-c71436aa1211)

![image](https://github.com/user-attachments/assets/c1fd7327-66b1-4400-8100-762949fa0beb)

[PSD-2874]: https://regulatorydelivery.atlassian.net/browse/PSD-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-09 14:17 UTC, alan-at-work requested changes

2024-08-09 14:17 UTC, alan-at-work commented on app/services/create_notification.rb
> +    notification.state = "submitted" unless from_task_list || its_product_bulk_upload
I am not sure what this is all about. It would appear you're over engineering this. 

`notification.state =  "submitted" unless from_task_list || from_bulk_product_upload` should be a simple fix?

2024-08-09 14:30 UTC, meeravnagesh requested changes

2024-08-09 14:30 UTC, meeravnagesh commented on app/services/create_notification.rb
> +  def its_product_bulk_upload
these methods are not needed , use the already existing bulk

2024-08-13 13:19 UTC, alan-at-work commented
Closing as there was a newer PR for this.

2024-08-13 13:19 UTC, closed without merging