added retired_at exclusion from search query ensuring only active products
OfficeForProductSafetyAndStandards/product-safety-database pull request #3193
Opened 2024-09-22 22:28 UTC by tahir-khalid

https://regulatorydelivery.atlassian.net/browse/PSD-3529

## Description

Fixed issue where retired products were being displayed in the product search results.

Incorrect results (showing two retired products):
![image](https://github.com/user-attachments/assets/9415a1bf-2c80-410e-a044-9b163eb3a56e)

Fix applied:
![image](https://github.com/user-attachments/assets/fcf64a8f-f4a7-4bb4-afa3-f729185cc4c9)

All products screen appears to already exclude retired products (checked view):
![image](https://github.com/user-attachments/assets/bb105bc1-e8ec-4b63-947c-f377cf9a5e29)

## Checklist:
- [x] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?

### General testing (author)
- [x] Test without JavaScript
- [x] Test on small screen

### Accessibility testing (author)
- [ ] Reviewed by Designer (if required)
- [x] Works keyboard only
- [x] Tested with one screen reader
- [x] Zoom page to 400% - content still visible
- [x] Disable CSS - does content make sense and appear in a logical order?

2024-09-24 14:55 UTC, meeravnagesh commented on spec/features/search_for_or_add_spec.rb
> +  scenario "Creating a notification add multiple products with one nonexistent product" do
reword:  one non existent product to "a product that does not exists"

and your scenario name says "Creating a notification add multiple products with one nonexistent product" it gives an impression that you are adding multiple products , but the scenario does not do that

2024-09-24 14:56 UTC, meeravnagesh commented on spec/features/search_for_or_add_spec.rb
> +    visit "/cases/your-cases"
the URL for PSD 2.0 is different , this URL will go to old controller and redirect you to new controller , add unnecessary routing

2024-09-24 15:02 UTC, meeravnagesh requested changes

2024-09-24 15:02 UTC, meeravnagesh commented on spec/features/search_for_or_add_spec.rb
> +    expect(page).to have_content("Create a product safety notification")
Once you reach the page end it with expect related to product , expect the product name as it there in the page , making sure that the product was added

2024-09-24 15:02 UTC, meeravnagesh commented on spec/features/search_for_or_add_spec.rb
> +    expect(page).to have_content("Create a product safety notification")
expect the product name as it there in the page , making sure that the product was added

2024-09-24 15:25 UTC, tahir-khalid commented on spec/features/search_for_or_add_spec.rb
> +  scenario "Creating a notification add multiple products with one nonexistent product" do
Changed to "Creating a notification add product existing product and a product that does not exist".

2024-09-27 14:17 UTC, tahir-khalid commented
This PR appears to have become detached in some way from my working branch and i really need to create another PR for the new work but I will first try to figure out why this is happening (git push -f isn't triggering checks).

2024-09-30 09:07 UTC, alan-at-work commented
Branch rebased

2024-09-30 09:55 UTC, meeravnagesh approved these changes

2024-09-30 10:14 UTC, merged