Ensured GTM script is called if not dev environment
OfficeForProductSafetyAndStandards/product-safety-database pull request #3229
Opened 2024-10-15 14:35 UTC by tahir-khalid

Ensured GTM script is firing at correct time and cookies_policy is being set.

2024-10-15 14:55 UTC, alan-at-work requested changes

2024-10-15 14:55 UTC, alan-at-work commented on app/views/layouts/application.html.erb
> +    <% if !Rails.env.development? %>
maybe use `<% unless Rails.env.development? %>` also why are we not checking the `analytics_cookies_accepted` now?

2024-10-15 14:55 UTC, alan-at-work commented on app/views/layouts/application.html.erb
> +    <% if !Rails.env.development? %>
as above maybe use `<% unless Rails.env.development? %>`

2024-10-15 14:55 UTC, alan-at-work commented on app/controllers/concerns/cookies_concern.rb
>        cookies[:cookies_policy] = {
Seems if you're not calling this is it really needed?

2024-10-16 08:28 UTC, tahir-khalid commented on app/views/layouts/application.html.erb
> +    <% if !Rails.env.development? %>
Reading John's email the issue seems to be the GTM container doesn't respond unless analytics cookie is accepted so the intention here is bypass that trigger the container regardless.

2024-10-16 08:34 UTC, alan-at-work commented on app/views/layouts/application.html.erb
> +    <% if !Rails.env.development? %>
that means you're not setting the cookie, I think they need to remove that and trust that we are dealing with it or update their code to use the one we have set.

2024-10-16 08:42 UTC, tahir-khalid commented on app/controllers/concerns/cookies_concern.rb
>        cookies[:cookies_policy] = {
Adjust code to ensure cookies policy is created.

2024-10-24 08:46 UTC, tahir-khalid commented
No longer required resolved in GTM 360 @ DBT

2024-10-24 08:46 UTC, closed without merging

2024-11-21 11:14 UTC, tahir-khalid commented
Closing as this is not needed now they used another cookie to trigger the container.