Implemented Phonelib, fixed breaking tests (multiple sms calls were n…
OfficeForProductSafetyAndStandards/product-safety-database pull request #3270
Opened 2024-11-19 08:06 UTC by tahir-khalid

## Description

Sentry reporting an error: InvalidPhoneError: Not a UK mobile number (Notifications::Client::BadRequestError)

Error occurring due to number not be formatted and validated correctly.

2024-11-19 13:14 UTC, meeravnagesh requested changes

2024-11-19 13:14 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    return nil if phone_number.nil?
the code will not reach this point if the phone_number is nil, unnecessary if condition ,

2024-11-19 13:14 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    return false if phone_number.nil?
the code will not reach this point if the phone_number is nil, unnecessary if condition ,

2024-11-19 13:14 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    parsed_number.valid? && parsed_number.country_code == "44" # Ensure it's a UK number
repeating the check , on country code , you have made sure its 44 at the end of normalise method, why do we need to check it again here

2024-11-19 13:14 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    return nil if phone_number.nil?
the Sentry error is on None and not Nil , hope you code also addresses the case where the Active record is returning None . Its not Cleary evident from you Rspec, please correct me if I am worng

2024-11-19 13:22 UTC, tahir-khalid commented on app/services/send_sms.rb
> +    return nil if phone_number.nil?
Defensive coding I had created this function previously and not taken into account that the nil check is already being done further up, thank you.

2024-11-19 13:22 UTC, tahir-khalid commented on app/services/send_sms.rb
> +    return false if phone_number.nil?
Defensive coding I had created this function previously and not taken into account that the nil check is already being done further up, thank you.

2024-11-19 13:26 UTC, tahir-khalid commented on app/services/send_sms.rb
> +    parsed_number.valid? && parsed_number.country_code == "44" # Ensure it's a UK number
This was a redundancy check have removed as its not necessary.

2024-11-20 10:55 UTC, meeravnagesh approved these changes

2024-11-20 11:33 UTC, alan-at-work approved these changes

2024-11-20 12:18 UTC, merged