Fix/psd 3930 action view template error
OfficeForProductSafetyAndStandards/product-safety-database pull request #3272
Opened 2024-11-20 18:19 UTC by tahir-khalid

## Description

Duplicate checks controller show view was encountering an error when the file object was nil added defensive code in the view and created spec file for coverage.

2024-11-20 20:59 UTC, meeravnagesh requested changes

2024-11-20 20:59 UTC, meeravnagesh commented on spec/views/show_html_spec.rb
> +require "rails_helper"
we don't have specs specifically for  htmls , probably this has to be a feature test -spec\features which had tests related to these

2024-11-20 20:59 UTC, meeravnagesh commented on spec/support/test_models.rb
> +# spec/support/test_models.rb
remove the comment -comment says test_model the class name is Test_upload_model

2024-11-20 20:59 UTC, meeravnagesh commented on app/views/products/duplicate_checks/show.html.erb
> +                        <%= image_tag(@image.file_upload, alt: sanitize(@image.file_upload&.filename&.to_s || 'Image'), class: 'opss-details-img') if @image&.file_upload %>
would it be not nice to say " Image not available" as alt rather than Image - questions like what image which image will arise if its only word Image

2024-11-21 10:31 UTC, tahir-khalid commented on spec/support/test_models.rb
> +# spec/support/test_models.rb
Reviewing features/adding_a_duplicate_product_spec.rb to see if I can add a feature test in there.  The spec I wrote specifically tests the image control and nil and related behaviours.

2024-11-25 11:49 UTC, meeravnagesh approved these changes

2024-11-29 09:21 UTC, merged