Send SMS - additional number format handling & code clean-up
OfficeForProductSafetyAndStandards/product-safety-database pull request #3273
Opened 2024-11-21 14:59 UTC by tahir-khalid

## Description

Sentry reporting an error: InvalidPhoneError: Not a UK mobile number (Notifications::Client::BadRequestError)

Added additional number format handling and clean up and updated spec to match.

2024-11-21 15:27 UTC, meeravnagesh requested changes

2024-11-21 15:27 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    Phonelib.parse(normalized_number).international.gsub(/[\s-]+/, "")
the input to this is already been cleansed and you have removed the space and -

2024-11-21 15:27 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    cleaned_number = phone_number.gsub(/[\s-]+/, "")
the phone_numer parameter is already gsubed

2024-11-21 21:19 UTC, meeravnagesh requested changes

2024-11-21 21:19 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    Phonelib.parse(normalized_number).international.gsub(/[\s-]+/, "")
![image](https://github.com/user-attachments/assets/85f47f0b-2bfd-42bf-afcf-bc50d5d5943f)

2024-11-21 21:19 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    Phonelib.parse(normalized_number).international.gsub(/[\s-]+/, "")
here the code in normalise UK number is removing spaces and in the end the Parse.international is adding spaces and then again your gsub is removing spaces

2024-11-21 21:19 UTC, meeravnagesh commented on app/services/send_sms.rb
> +    Phonelib.parse(normalized_number).international.gsub(/[\s-]+/, "")
remove this line - its not needed anymore if you dont want spaces

2024-11-21 21:19 UTC, meeravnagesh commented on app/services/send_sms.rb
>    def valid_phone_number?(phone_number)
for your new case/requirement , this below code reckon below code is enough
private

  def validate_and_format_phone_number(phone_number)
    return nil if phone_number.nil?

    normalized_number = normalize_uk_number(phone_number)
    return nil unless valid_phone_number?(normalized_number)
    normalized_number
  end

  def normalize_uk_number(phone_number)
    cleaned_number = phone_number.gsub(/[\s-]+/, "")
    return cleaned_number if cleaned_number.start_with?(UK_PREFIX)

    if cleaned_number.match?(UK_LEADING_ZERO)
      return UK_PREFIX + cleaned_number.gsub(UK_LEADING_ZERO, "")
    end

    UK_PREFIX + cleaned_number
  end

  def valid_phone_number?(phone_number)
    Phonelib.parse(phone_number).valid?
  end
end

2024-11-21 21:19 UTC, meeravnagesh commented on app/services/send_sms.rb
>    def valid_phone_number?(phone_number)
in normalised the UK number and added a prefix +44, no need to check again
parsed_number.valid? && parsed_number.country_code == "44" # Ensure it's a UK number

2024-11-22 10:26 UTC, tahir-khalid commented on app/services/send_sms.rb
> +    Phonelib.parse(normalized_number).international.gsub(/[\s-]+/, "")
Refactored.

2024-11-22 10:29 UTC, tahir-khalid commented on app/services/send_sms.rb
>    def valid_phone_number?(phone_number)
Implemented.

2024-11-22 10:57 UTC, meeravnagesh approved these changes

2024-11-22 11:15 UTC, merged