Implemented CSP and HSTS
OfficeForProductSafetyAndStandards/product-safety-database pull request #3274
Opened 2024-11-22 11:47 UTC by tahir-khalid

## Description

PSD-3985

Missing or Misconfigured Application Security Headers - A number of HTTP headers which can be used to enhance the security posture of the web application were not used.

Implemented CSP and HSTS support in the rails app.

2024-11-28 16:40 UTC, tahir-khalid commented on config/initializers/content_security_policy.rb
> +Rails.application.config.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
Confirmed no other changes needed.

2024-12-05 09:43 UTC, tahir-khalid commented
> Looks ok, I would like to know how this is going to be tested and verified please. How would you get Venu to test for example?

@alan-at-work I have updated the QA ticket with instructions (https://regulatorydelivery.atlassian.net/browse/PSD-3988) that should be adequate for Venu to test.

2024-12-06 10:15 UTC, alan-at-work approved these changes

2024-12-06 10:57 UTC, meeravnagesh requested changes

2024-12-06 10:57 UTC, meeravnagesh commented on config/initializers/content_security_policy.rb
> +  policy.style_src(*trusted_style_sources)
One question , I may not be asking relevant but we use lots of components from Gov UK designs , so when we say trusted font and trusted source  is just google... , will it not affect the gov uk components ?

i might be wrong :) let me know

2024-12-06 12:19 UTC, tahir-khalid commented on config/initializers/content_security_policy.rb
> +  policy.style_src(*trusted_style_sources)
Updated CSP entries to match the latest GOV UK Design requirements.

2024-12-11 15:49 UTC, meeravnagesh commented on config/initializers/content_security_policy.rb
> +  policy.style_src(*trusted_style_sources)
we have added gov.uk pattern to the trusted sites

2024-12-11 16:12 UTC, meeravnagesh approved these changes

2024-12-12 16:08 UTC, merged