Set devise timeout 30 minutes
OfficeForProductSafetyAndStandards/product-safety-database pull request #3275
Opened 2024-11-22 12:57 UTC by tahir-khalid

## Description

Long HTTP Session Timeout - A review of the device identified that an excessive HTTP timeout was configured.

Set devise session timeout to 30 minutes.

2024-11-25 11:45 UTC, meeravnagesh requested changes

2024-11-25 11:45 UTC, meeravnagesh commented on spec/features/sign_in_spec.rb
> +    travel_to 31.hours.from_now do
check for 29 minutes and 31 minutes

2024-11-25 11:45 UTC, meeravnagesh commented on spec/features/sign_in_spec.rb
> +    travel_to 31.hours.from_now do
the code is in hours

2024-11-28 21:52 UTC, meeravnagesh requested changes

2024-11-28 21:52 UTC, meeravnagesh commented on spec/features/redirect_after_2fa_spec.rb
>        visit "/teams/#{team.id}/invitations/new"
you missed removing this line

2024-11-29 10:16 UTC, tahir-khalid commented on spec/features/sign_in_spec.rb
> +      expect(page).to have_text("If you don’t have an account, ask someone in your team to send you an invite")
No not during my testing which is why I was having issues getting the tests completed unexpected results so I adjusted the tests.

2024-11-29 12:27 UTC, meeravnagesh commented on spec/features/invite_user_spec.rb
> +      Capybara.current_session.reset!
what is the reason for session reset ?

2024-12-09 11:43 UTC, tahir-khalid commented on spec/features/redirect_after_2fa_spec.rb
>        visit "/teams/#{team.id}/invitations/new"
TODO: remove the visit line and retest

2024-12-12 10:27 UTC, alan-at-work commented
once updated with new timeouts, update the tests too and make sure we have all as **green**

2024-12-12 11:04 UTC, meeravnagesh requested changes

2024-12-12 11:04 UTC, meeravnagesh commented on spec/features/invite_user_spec.rb
> -      travel_to(4.hours.ago) do
do we need this change now , 4 hours would also work right ?

2024-12-12 16:09 UTC, tahir-khalid commented on spec/features/invite_user_spec.rb
> -      travel_to(4.hours.ago) do
Reverted

2024-12-12 16:35 UTC, meeravnagesh approved these changes

2024-12-12 17:05 UTC, merged