Implemented devise-security gem
OfficeForProductSafetyAndStandards/product-safety-database pull request #3292
Opened 2024-12-11 10:57 UTC by tahir-khalid

## Description

Concurrent Session Logins - The application was found to allow concurrent session logins.

Installed `devise-security` gem

2024-12-11 11:16 UTC, meeravnagesh requested changes

2024-12-11 11:16 UTC, meeravnagesh commented on config/locales/devise.security_extension.by.yml
> +  errors:
why do we need different - so many locales , is PSD available in different languages?

2024-12-11 11:16 UTC, meeravnagesh commented on config/initializers/devise_security.rb
> +  # Configure security extension for devise
why is everything commented ?

2024-12-11 11:16 UTC, meeravnagesh commented on docker/db/Dockerfile
> +FROM postgres:17
why is the postgres upgraded ? do we know if the Gov pass supports version 17

2024-12-11 11:23 UTC, tahir-khalid commented on config/locales/devise.security_extension.by.yml
> +  errors:
These were installed by the gym I will test if they can be removed.

2024-12-11 11:28 UTC, tahir-khalid commented on config/initializers/devise_security.rb
> +  # Configure security extension for devise
This is how the gem provides the configuration file (removed comments).

2024-12-11 11:43 UTC, tahir-khalid commented on docker/db/Dockerfile
> +FROM postgres:17
I had to upgrade to version 17 as I was unable to get the gem to work with version 11 and later versions.   I discussed this with @alan-at-work who advised it was okay to user the latest version.

If we need to stay on version 11 then we need to review an alternative solution to using a gem (more code involved and bit as bullet proof as the gem).

2024-12-11 11:50 UTC, meeravnagesh commented on app/models/user.rb
> +  def force_session_timeout?
is this a common way of implementing this method. the comment says # custom logic here, and the line is return true

2024-12-11 11:51 UTC, meeravnagesh commented on config/initializers/devise_security.rb
> +# frozen_string_literal: true
# frozen_string_literal: true - comment

2024-12-11 11:51 UTC, meeravnagesh commented on config/initializers/devise_security.rb
> +  # https://github.com/devise-security/devise-security?tab=readme-ov-file#configuration
do we need these comments

2024-12-11 11:52 UTC, meeravnagesh commented on db/migrate/20241211101216_add_session_limitable_to_users.rb
> +class AddSessionLimitableToUsers < ActiveRecord::Migration[7.1]
if are introducing a new table should we inform CDS, ? @alan-at-work ?

2024-12-11 11:52 UTC, meeravnagesh commented on docker/db/Dockerfile
> +FROM postgres:17
@alan-at-work can you please confirm

2024-12-11 12:34 UTC, tahir-khalid commented on app/models/user.rb
> +  def force_session_timeout?
Removed as its not necessary the gem is taking care of the session.

2024-12-11 12:35 UTC, tahir-khalid commented on config/initializers/devise_security.rb
> +  # https://github.com/devise-security/devise-security?tab=readme-ov-file#configuration
Reference to the gem documentation if we ever want to enable any options for the configuration.

2024-12-12 10:23 UTC, alan-at-work commented on docker/db/Dockerfile
> +FROM postgres:17
can update to 17, it will be done as part of the migration. but you will also need to test to make sure the schema works. AND a way to migrate data over. @meeravnagesh @tahir-khalid

2024-12-12 10:24 UTC, alan-at-work commented on config/initializers/devise_security.rb
> +# frozen_string_literal: true
rubocop sometimes adds this

2024-12-16 10:05 UTC, meeravnagesh commented on db/migrate/20241211101216_add_session_limitable_to_users.rb
> +class AddSessionLimitableToUsers < ActiveRecord::Migration[7.1]
agreeing with Alan , as its not a new table

2024-12-17 21:07 UTC, meeravnagesh approved these changes

2024-12-18 16:22 UTC, merged